name: "New Task"
description: "(FOR DEVELOPERS) Create a new development task for ThesisFlow."
title: "short description"
labels: [task]
projects: [Jed556/7]
body:
  - type: markdown
    attributes:
      value: "Please complete the form below to create a new development task."
  - type: input
    id: task-summary
    attributes:
      label: "Task summary"
      description: "Briefly describe the new task."
      placeholder: "A short summary of the task."
    validations:
      required: true
  - type: textarea
    id: task-details
    attributes:
      label: "Task details"
      description: "Provide a detailed description of the task to be completed."
      placeholder: "Describe the specific actions or steps required for this task."
    validations:
      required: true
  - type: textarea
    id: task-how
    attributes:
      label: "Proposed approach or solution"
      description: "Describe possible approaches, methods, or steps to accomplish this task."
      placeholder: "Explain how this task could be completed or suggest ways to tackle it."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots here."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Please add a label that best describes the task (`bug`, `feat`, `test`, `docs`)."