import type { UserRole } from './profile';

/**
 * Expert request status - limited to request workflow states
 */
export type ExpertRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * Mentor request role - subset of UserRole for mentor-specific operations
 */
export type MentorRequestRole = 'adviser' | 'editor' | 'statistician';

/**
 * Firestore document describing a single mentor assignment request generated by a group.
 */
export interface ExpertRequest {
    id: string;
    expertUid: string;
    role: UserRole;
    requestedBy: string;
    message?: string;
    status: ExpertRequestStatus;
    createdAt: string;
    updatedAt: string;
    respondedAt?: string | null;
    responseNote?: string | null;
    /** @deprecated Use parent path to determine groupId */
    groupId?: string;
    /** @deprecated Use expertUid instead */
    mentorUid?: string;
}
