import type { UserRole } from './profile';

/**
 * Expert request status - limited to request workflow states
 */
export type ExpertRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * Expert request role - subset of UserRole for expert-specific operations
 */
export type ExpertRequestRole = 'adviser' | 'editor' | 'statistician';

/**
 * Firestore document describing a single expert assignment request generated by a group.
 */
export interface ExpertRequest {
    id: string;
    expertUid: string;
    role: UserRole;
    requestedBy: string;
    message?: string;
    status: ExpertRequestStatus;
    createdAt: string;
    updatedAt: string;
    respondedAt?: string | null;
    responseNote?: string | null;
    /** Group ID extracted from document path */
    groupId?: string;
}
