/**
 * Supported mentor roles that can receive student requests.
 */
export type MentorRequestRole = 'adviser' | 'editor' | 'statistician';

/**
 * Workflow states for mentor assignment requests.
 */
export type MentorRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * Firestore document describing a single mentor assignment request generated by a group.
 */
export interface MentorRequest {
    id: string;
    groupId: string;
    mentorUid: string;
    role: MentorRequestRole;
    requestedBy: string;
    message?: string;
    status: MentorRequestStatus;
    createdAt: string;
    updatedAt: string;
    respondedAt?: string | null;
    responseNote?: string | null;
}
