// Re-export from centralized config for backwards compatibility
export {
    // Active constants
    FIRESTORE_IN_QUERY_LIMIT,
    FIRESTORE_BATCH_WRITE_LIMIT,
    THESIS_STAGE_SLUGS,
    DEFAULT_DEPARTMENT_SEGMENT,
    DEFAULT_COURSE_SEGMENT,
    DEFAULT_YEAR,

    // Subcollection names
    GROUPS_SUBCOLLECTION,
    THESIS_SUBCOLLECTION,
    STAGES_SUBCOLLECTION,
    CHAPTERS_SUBCOLLECTION,
    SUBMISSIONS_SUBCOLLECTION,
    CHATS_SUBCOLLECTION,
    PROPOSALS_SUBCOLLECTION,
    EXPERT_REQUESTS_SUBCOLLECTION,
    AUDITS_SUBCOLLECTION,
    TERMINAL_SUBCOLLECTION,
    USERS_SUBCOLLECTION,
    CONFIGURATION_ROOT,
} from '../../../config/firestore';
