// Re-export from centralized config for backwards compatibility
export {
    // Legacy collection names (deprecated)
    THESES_COLLECTION,
    PANEL_COMMENTS_COLLECTION,
    TERMINAL_REQUIREMENT_SUBMISSIONS_COLLECTION,
    GROUPS_COLLECTION,
    TOPIC_PROPOSALS_COLLECTION,
    USERS_COLLECTION,
    FILES_COLLECTION,
    CALENDARS_COLLECTION,
    EVENTS_COLLECTION,
    MENTOR_REQUESTS_COLLECTION,
    CHAPTERS_COLLECTION,
    TERMINAL_REQUIREMENT_CONFIGS_COLLECTION,

    // Active constants
    FIRESTORE_IN_QUERY_LIMIT,
    FIRESTORE_BATCH_WRITE_LIMIT,
    THESIS_STAGE_SLUGS,
    DEFAULT_DEPARTMENT_SEGMENT,
    DEFAULT_COURSE_SEGMENT,
    DEFAULT_YEAR,

    // Subcollection names
    GROUPS_SUBCOLLECTION,
    THESIS_SUBCOLLECTION,
    STAGES_SUBCOLLECTION,
    CHAPTERS_SUBCOLLECTION,
    SUBMISSIONS_SUBCOLLECTION,
    CHATS_SUBCOLLECTION,
    PROPOSALS_SUBCOLLECTION,
    EXPERT_REQUESTS_SUBCOLLECTION,
    AUDITS_SUBCOLLECTION,
    TERMINAL_SUBCOLLECTION,
    USERS_SUBCOLLECTION,
    CONFIGURATION_ROOT,
} from '../../../config/firestore';
